#!/data/data/com.termux/files/usr/bin/bash
# =============================================================================
# PocketAI — Termux Setup Script
# Runs ON the Android phone inside Termux
# =============================================================================

set -euo pipefail

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
step() { echo -e "\n${CYAN}▶ $1${NC}"; }
ok()   { echo -e "  ${GREEN}✓ $1${NC}"; }
warn() { echo -e "  ${YELLOW}⚠ $1${NC}"; }
fail() { echo -e "  ${RED}✗ $1${NC}"; exit 1; }
info() { echo -e "  $1"; }

echo -e "\n${CYAN}${BOLD}PocketAI — Phone Setup${NC}\n"

# ── Grant storage access ──────────────────────────────────────────────────────
step "Requesting storage permission"
info "You may see a permission dialog — tap ALLOW"
termux-setup-storage 2>/dev/null || true
sleep 2
ok "Storage access configured"

# ── Update packages ───────────────────────────────────────────────────────────
step "Updating Termux packages"
pkg update -y -q 2>/dev/null
ok "Packages updated"

# ── Detect USB drive ──────────────────────────────────────────────────────────
step "Detecting flash drive"

DRIVE_UUID=""
MOUNT_POINT=""

for uuid in $(ls /storage/ 2>/dev/null | grep -v emulated | grep -v self); do
  if [ -d "/storage/$uuid/pocketai" ]; then
    DRIVE_UUID="$uuid"
    MOUNT_POINT="/storage/$uuid"
    break
  fi
done

if [ -z "$DRIVE_UUID" ]; then
  # Try without pocketai subfolder
  for uuid in $(ls /storage/ 2>/dev/null | grep -v emulated | grep -v self); do
    if [ -d "/storage/$uuid" ]; then
      DRIVE_UUID="$uuid"
      MOUNT_POINT="/storage/$uuid"
      warn "Found drive at /storage/$uuid but no pocketai/ folder."
      warn "Make sure you ran: bash setup/deploy_to_drive.sh on your computer first."
      break
    fi
  done
fi

[ -z "$DRIVE_UUID" ] && fail "No USB drive detected. Plug in your flash drive and retry."
ok "Drive found: $MOUNT_POINT"

POCKETAI_DIR="$MOUNT_POINT/pocketai"
ENGINE="$POCKETAI_DIR/engine/llama-server"
SCRIPTS_DIR="$POCKETAI_DIR/scripts"

# ── Check engine ──────────────────────────────────────────────────────────────
step "Checking inference engine"

if [ ! -f "$ENGINE" ]; then
  warn "llama-server binary not found at $ENGINE"
  warn "The engine must be compiled for Android ARM64 on your computer."
  warn "Run: bash setup/build_engine.sh on your dev machine, then redeploy."
  fail "Cannot continue without engine binary."
fi

chmod +x "$ENGINE"
ok "Engine found and executable"

# ── Find a model ──────────────────────────────────────────────────────────────
step "Detecting models"

MODELS_DIR="$POCKETAI_DIR/models"
MODEL_FILE=""
MODEL_TIER=""

# Prefer nano for compatibility, then mid, then full
for tier_file in \
  "qwen2.5-1.5b-instruct-q4_k_m.gguf:nano" \
  "qwen2.5-3b-instruct-q4_k_m.gguf:mid" \
  "qwen2.5-7b-instruct-q4_k_m.gguf:full"
do
  fname="${tier_file%%:*}"
  tier="${tier_file##*:}"
  if [ -f "$MODELS_DIR/$fname" ]; then
    MODEL_FILE="$MODELS_DIR/$fname"
    MODEL_TIER="$tier"
    ok "Found $tier model: $fname"
    break
  fi
done

[ -z "$MODEL_FILE" ] && fail "No model files found in $MODELS_DIR. Run download_model.sh on your computer first."

# ── Detect available RAM ──────────────────────────────────────────────────────
step "Checking device RAM"

TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
AVAIL_RAM_KB=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
TOTAL_RAM_GB=$(echo "scale=1; $TOTAL_RAM_KB / 1048576" | bc)
AVAIL_RAM_GB=$(echo "scale=1; $AVAIL_RAM_KB / 1048576" | bc)

info "Total RAM: ${TOTAL_RAM_GB} GB"
info "Available: ${AVAIL_RAM_GB} GB"

# Select context size based on RAM
AVAIL_MB=$(( AVAIL_RAM_KB / 1024 ))
if [ "$AVAIL_MB" -lt 900 ]; then
  CTX_SIZE=1024
  THREADS=2
  warn "Very low RAM. Using minimal context (1024 tokens)."
elif [ "$AVAIL_MB" -lt 1800 ]; then
  CTX_SIZE=2048
  THREADS=4
  info "Using standard context (2048 tokens)"
else
  CTX_SIZE=4096
  THREADS=4
  info "Using extended context (4096 tokens)"
fi

ok "RAM profile: ctx=$CTX_SIZE threads=$THREADS"

# ── Write the launch script ───────────────────────────────────────────────────
step "Writing launch script"

LAUNCH_SCRIPT="$SCRIPTS_DIR/launch.sh"
mkdir -p "$SCRIPTS_DIR"

cat > "$LAUNCH_SCRIPT" << LAUNCHEOF
#!/data/data/com.termux/files/usr/bin/bash
# PocketAI Launch Script — auto-generated by termux_setup.sh

ENGINE="$ENGINE"
MODEL="$MODEL_FILE"
PORT=8080
CTX=$CTX_SIZE
THREADS=$THREADS

echo ""
echo "  ▸ PocketAI Inference Server"
echo "  ▸ Model: $(basename "$MODEL_FILE")"
echo "  ▸ Context: \$CTX tokens | Threads: \$THREADS"
echo "  ▸ Listening on http://127.0.0.1:\$PORT"
echo ""
echo "  Open Chrome and navigate to:"
echo "  file://$POCKETAI_DIR/app/index.html"
echo ""
echo "  Press Ctrl+C to stop"
echo ""

\$ENGINE \\
  --model "\$MODEL" \\
  --host 127.0.0.1 \\
  --port \$PORT \\
  --ctx-size \$CTX \\
  --threads \$THREADS \\
  --n-gpu-layers 0 \\
  --no-mmap false \\
  --log-disable \\
  --parallel 1
LAUNCHEOF

chmod +x "$LAUNCH_SCRIPT"
ok "Launch script written: $LAUNCH_SCRIPT"

# ── Write shortcut ────────────────────────────────────────────────────────────
SHORTCUT="$HOME/.shortcuts/pocketai"
mkdir -p "$HOME/.shortcuts"
cat > "$SHORTCUT" << SHORTEOF
#!/data/data/com.termux/files/usr/bin/bash
bash $LAUNCH_SCRIPT
SHORTEOF
chmod +x "$SHORTCUT"
ok "Termux Widget shortcut created (install Termux:Widget app to use)"

# ── Quick inference test ──────────────────────────────────────────────────────
step "Running quick inference test (10 tokens)"
info "This confirms the engine + model work on your device..."

TEST_RESULT=$("$ENGINE" \
  --model "$MODEL_FILE" \
  --prompt "Hello" \
  --n-predict 10 \
  --threads "$THREADS" \
  --ctx-size 128 \
  --log-disable \
  --no-mmap false 2>/dev/null | tail -1 || echo "TEST_FAILED")

if [[ "$TEST_RESULT" == "TEST_FAILED" ]] || [ -z "$TEST_RESULT" ]; then
  warn "Quick test inconclusive (this is sometimes normal). Try launching and see."
else
  ok "Inference test passed: $TEST_RESULT"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║       Phone Setup Complete! ✓                 ║${NC}"
echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}To start PocketAI:${NC}"
echo ""
echo -e "  ${CYAN}bash $LAUNCH_SCRIPT${NC}"
echo ""
echo -e "  Then open Chrome and go to:"
echo -e "  ${CYAN}file://$POCKETAI_DIR/app/index.html${NC}"
echo ""
echo -e "  Or install ${BOLD}Termux:Widget${NC} from F-Droid for a home screen button."
echo ""
